In [1]:
!pip install scikit-learn-extra


In [2]:
from sklearn_extra.cluster import KMedoids


In [3]:
import numpy as np

In [5]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [9]:
x = [[1, 2], [1, 4], [1, 0],
                [4, 2], [4, 4], [4, 0]]
type(x)

list

In [13]:
X = np.asarray(x)
type(X)

numpy.ndarray

In [25]:
X.shape

(6, 2)

In [14]:
kmedoids = KMedoids(n_clusters=2, random_state=0)

In [15]:
kmedoids.fit(X)

KMedoids(n_clusters=2, random_state=0)

In [16]:
kmedoids.labels_

array([0, 0, 0, 1, 1, 1], dtype=int64)

In [21]:
kmedoids.predict([[0,0],[5,4]])

array([0, 1], dtype=int64)

In [23]:
kmedoids.cluster_centers_

array([[1, 2],
       [4, 2]])

In [24]:
kmedoids.inertia_

8.0